language: go
go: 1.14.2

branches:
  only:
    - master
    - feature/*
    - issue/*

before_install:
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then choco update; fi
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then choco install hub; fi
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then choco install make; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew update; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install hub; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then snap install hub --classic; fi

jobs:
  include:
    - os: linux
      dist: bionic
      script:
        - pushd sender
        - make build-release
        - popd
        - pushd receiver
        - make build-release
        - popd
        - make release
        - make release-binaries

    - os: osx
      osx_image: xcode11.3
      script:
        - pushd sender
        - make build-release
        - popd
        - pushd receiver
        - make build-release
        - popd
        - make release
        - make release-binaries

    - os: windows
      script:
        - pushd sender
        - make build-release
        - popd
        - pushd receiver
        - make build-release
        - popd
        - make release
        - make release-binaries