name: ehs
summary: A cli to send events (messages) to Azure Event Hubs
description: |
  With this cli you can send events to event hubs in different ways.
  You can send single event, batch, with repetition and more.
version: git
base: core18
adopt-info: "event-hub-cli"
confinement: classic

parts:
  ehs:
    plugin: go
    go-importpath: sender
    source: https://github.com/azure-open-tools/event-hubs-cli
    source-type: git
    build-packages: [make]

apps:
  ehs-test:
    command: bin/ehs